name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    environment: master

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker registry
        uses: docker/login-action@v3
        with:
          registry: registry.ilyasabdut.loseyourip.com
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and Push ARM Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: registry.ilyasabdut.loseyourip.com/personal-portfolio-ai:latest

  deployment:
    needs: build
    runs-on: ubuntu-latest
    environment: master
    steps:
      - name: Connect to Tailscale
        uses: tailscale/github-action@v3
        with:
          # oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          # oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          # tags: tag:ci
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

      - name: SSH and Restart Container
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_TAILSCALE_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            echo "Deploying on $(hostname)"
            cd /home/ubuntu/composes/portfolio-ai

            echo "Logging into private Docker registry..."
            echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login registry.ilyasabdut.loseyourip.com -u "${{ secrets.REGISTRY_USERNAME }}" --password-stdin

            echo "Pulling latest image..."
            docker compose pull

            echo "Restarting container..."
            docker compose down
            docker compose up -d

            echo "Deployment finished!"
          debug: true
          timeout: 60s
          command_timeout: 10m
